### ISSUE TITLE
How to customise default border

### ISSUE THREAD

**Issue by Lyudol** [mathquill/mathquill#1035]
I can't at all seem to figure out how to edit that default blue border around a focused input box. I can't find it in the documentation or anything. Does anyone know how to do this?

**Comment by nedredmond** [comment]
You would just need to target it with CSS, like so:
```css
.mq-editable-field.mq-focused {
  box-shadow: unset;
  border-color: unset;
}
```
